### ISSUE TITLE
Content Creation Issues

### ISSUE THREAD

**Issue by sakinshrestha** [FameThemes/screenr#60]
- All your options from FrontPage Settings that create content, like textarea, input boxes, etc all falls under
- More info
  - https://make.wordpress.org/themes/2015/06/02/content-creation-discussion-examples/
  - http://justintadlock.com/archives/2015/05/28/the-theme-review-teams-content-creation-discussion

**Comment by shrimp2t** [comment]
@KienTrong

**Comment by KienTrong** [comment]
@sakinshrestha Hi Sakin, thanks for the review.

Those textarea and input boxes you referring to are section title, sub-title, some section has short description text and I think it's trivial content. The actual section content pull content from page or post which won't lose when users switch to other themes.

Would like to see input from Justin on this as well @justintadlock

**Comment by justintadlock** [comment]
I'll look this over too and let you know what I think of it.

**Comment by justintadlock** [comment]
Some of this is OK but in a very gray area for inclusion on WordPress.org.  The one-off fields like the About section are considered trivial content and would get a pass.

These wouldn't be allowed:
- Hero Items
- Counter Items
- Client Items

Those type of repeatable fields are what TRT calls _pseudo CPTs_ and should be left to plugins.  Or, rather, themes should show a user's existing content.  The way the "Services" section is handled is a good example of how you'd want to do the above sections.

Other items could be better handled like so:
- Video - Pull from the "video" post format.

**Comment by KienTrong** [comment]
Hi @justintadlock sorry for any late.
1. The Hero item, I think it can be consider as trivial content because there is only one item and it contain a small amount of text, it's setup like the OnePress theme which you had review some months ago.
2. A question about Client section: Client item only contain image, no meta data and it pull image from media files which won't lose when user switch to different theme, just like page or post.
3. The counter content can considered is trivial too, just a number and 3 words. I keep follow the review guidelines as much as possible, like OnePress theme has it and it's passed.

If Testimonials, Team section includes in theme then it's content creation issue, for these above I really think it can be consider as trivial content.

Let me know.

**Comment by justintadlock** [comment]
I'm not sure which theme OnePress is.  I look over a lot of themes on WordPress.org, but the work I do there is outside the scope of this theme review.  ThemeReview.co goes above and beyond what WordPress.org expects because we want you to build a better theme.  What we're doing here is giving you our opinion on things you should change in your theme.  Ultimately, that decision will fall to you.

We want you to think about ways that you can make the theme better by making changes, not debate about whether something is allowed on WordPress.org. 

Now that I'm looking over this a bit more, I really think the architecture of the front page needs work.  It's not about the UI.  That's mostly fine.  It's about how the data is stored.  Essentially, the theme is storing most of the content of the front page as a theme setting.

One thing to consider is creating a bit of a "mini page-builder" (for lack of a better term).  All of this custom content could be stored in the page's `post_content` field, for example (yes, this can be done directly from the customizer).

Get out of this mode of following what everyone else is doing.  Try thinking outside the box a bit while doing everything you can to make sure that a user has their content available to them when they switch themes in the future (yes, even the "trivial" content).

---

Just a note on the "Hero Items".  I had assumed you planned to allow more items there.  You might want to change that to "Hero Item".

**Comment by KienTrong** [comment]
Hi Justin (@justintadlock), got your means now. You opened my mind with all your suggestions.

Regarding the mini page-builder you mention above, we had built a simple version of a builder that use `post_content`to stored data : https://cl.ly/0u2F170e1P1X, by default it has native builder items such as Image, Gallery, Editor. The project stopped some weeks ago for continue discuss because some time I think it's just like many page builder out there, nothing new that can get love & surprise from users.

Customizer provider a full setting API and simple UI which users familiar with, plus we can include it in theme that can be use to WordPress.org. And we can use it for all pages not just front page, something like Layerswp (http://layerswp.com/) already do.

Would like to keep the Screenr theme as is because a lot of works went to this, will get these things above into a new theme and may need your input/suggestion in future :smile:

Btw, here is the OnePress[ trac ticket](https://themes.trac.wordpress.org/ticket/27818#comment:12) 

Thank you.
